// Avatar customization options for DiceBear Big Smile style
export const AVATAR_OPTIONS = {
  backgroundColor: [
    { label: 'Light Blue', value: 'b6e3f4' },
    { label: 'Light Purple', value: 'c0aede' },
    { label: 'Light Lavender', value: 'd1d4f9' },
    { label: 'Light Pink', value: 'ffd5dc' },
    { label: 'Light Peach', value: 'ffdfbf' },
    { label: 'Light Green', value: 'c7f9cc' },
    { label: 'Light Yellow', value: 'fff2cc' },
    { label: 'Light Coral', value: 'fca5a5' },
    { label: 'Light Teal', value: '5eead4' },
  ],
  skinColor: [
    { label: 'Very Light', value: 'ffe4c0' },
    { label: 'Light', value: 'f5d7b1' },
    { label: 'Light Medium', value: 'efcc9f' },
    { label: 'Medium', value: 'e2ba87' },
    { label: 'Medium Dark', value: 'c99c62' },
    { label: 'Dark', value: 'a47539' },
    { label: 'Very Dark', value: '8c5a2b' },
    { label: 'Deep', value: '643d19' },
  ],
  hair: [
    { label: 'Short Hair', value: 'shortHair' },
    { label: 'Mohawk', value: 'mohawk' },
    { label: 'Wavy Bob', value: 'wavyBob' },
    { label: 'Bowl Cut', value: 'bowlCutHair' },
    { label: 'Curly Bob', value: 'curlyBob' },
    { label: 'Straight Hair', value: 'straightHair' },
    { label: 'Braids', value: 'braids' },
    { label: 'Shaved Head', value: 'shavedHead' },
    { label: 'Bun Hair', value: 'bunHair' },
    { label: 'Fro Bun', value: 'froBun' },
    { label: 'Bangs', value: 'bangs' },
    { label: 'Half Shaved', value: 'halfShavedHead' },
    { label: 'Curly Short', value: 'curlyShortHair' },
  ],
  hairColor: [
    { label: 'Dark Brown', value: '220f00' },
    { label: 'Brown', value: '3a1a00' },
    { label: 'Light Brown', value: '71472d' },
    { label: 'Blonde', value: 'e2ba87' },
    { label: 'Purple', value: '605de4' },
    { label: 'Teal', value: '238d80' },
    { label: 'Orange', value: 'd56c0c' },
    { label: 'Yellow', value: 'e9b729' },
  ],
  eyes: [
    { label: 'Cheery', value: 'cheery' },
    { label: 'Normal', value: 'normal' },
    { label: 'Confused', value: 'confused' },
    { label: 'Starstruck', value: 'starstruck' },
    { label: 'Winking', value: 'winking' },
    { label: 'Sleepy', value: 'sleepy' },
    { label: 'Sad', value: 'sad' },
    { label: 'Angry', value: 'angry' },
  ],
  mouth: [
    { label: 'Open Smile', value: 'openedSmile' },
    { label: 'Unimpressed', value: 'unimpressed' },
    { label: 'Gap Smile', value: 'gapSmile' },
    { label: 'Open Sad', value: 'openSad' },
    { label: 'Teeth Smile', value: 'teethSmile' },
    { label: 'Awkward Smile', value: 'awkwardSmile' },
    { label: 'Braces', value: 'braces' },
    { label: 'Kawaii', value: 'kawaii' },
  ],
  accessories: [
    { label: 'None', value: 'none' },
    { label: 'Cat Ears', value: 'catEars' },
    { label: 'Glasses', value: 'glasses' },
    { label: 'Crown', value: 'sailormoonCrown' },
    { label: 'Clown Nose', value: 'clownNose' },
    { label: 'Sleep Mask', value: 'sleepMask' },
    { label: 'Sunglasses', value: 'sunglasses' },
    { label: 'Face Mask', value: 'faceMask' },
    { label: 'Mustache', value: 'mustache' },
  ],
} as const;

// Default avatar settings
export const getDefaultAvatarSettings = () => ({
  style: 'big-smile',
  seed: 'default',
  backgroundColor: ['b6e3f4'],
  skinColor: ['ffe4c0'],
  hair: ['shortHair'],
  hairColor: ['220f00'],
  eyes: ['normal'],
  mouth: ['openedSmile'],
  accessories: ['none'],
  accessoriesChance: 0,
});

// Pronoun options
export const PRONOUN_OPTIONS = [
  'he/him',
  'she/her',
  'they/them',
  'he/they',
  'she/they',
  'any pronouns',
  'ask me',
  'prefer not to say',
] as const;
